export {default as image_1} from '../assets/images/img1.png'
export {default as image_2} from '../assets/images/img2.png'
export {default as buildingIcon} from '../assets/icons/Building.png'
export {default as bathIcon} from '../assets/icons/bathTop.png'
export {default as areaIcon} from '../assets/icons/area.png'
export {default as locationIcon} from '../assets/icons/location.png'
export {default as vectorIcon} from '../assets/icons/Vector.png'

// questionIcons 
export {default as carChangerIcon} from '../assets/questionIcons/Car Charger.png'
export {default as newYorkIcon} from '../assets/questionIcons/New York.png'
export {default as lockerIcon} from '../assets/questionIcons/Locker.png'
export {default as elvatorIcon} from '../assets/questionIcons/Elevator.png'
export {default as sunloungerIcon} from '../assets/questionIcons/Sun Lounger.png'
export {default as livingRoomIcon} from '../assets/questionIcons/Living Room.png'
export {default as meetingRoomIcon} from '../assets/questionIcons/Meeting Room.png'
export {default as GameController} from '../assets/questionIcons/Game Controller.png'
export {default as pavillionIcon} from '../assets/questionIcons/Pavilion.png'
export {default as dumbbellIcon} from '../assets/questionIcons/Dumbbell.png'
export {default as basketBallIcon} from '../assets/questionIcons/Basketball.png'
export {default as tennisCourtIcon} from '../assets/questionIcons/Tennis Racquet.png'
export {default as swimmingIcon} from '../assets/questionIcons/Swimming.png'
export {default as weberIcon} from '../assets/questionIcons/Weber.png'
export {default as rowOfSeatsIcon} from '../assets/questionIcons/Row of seats.png'
export {default as bambooIcon} from '../assets/questionIcons/Bamboo.png'
export {default as valetParkingIcon} from '../assets/questionIcons/Valet Parking.png'
export {default as indoorParkingIcon} from '../assets/questionIcons/Indoor Parking.png'
export {default as gargeIcon} from '../assets/questionIcons/Garage.png'
export {default as bikeParkingIcon} from '../assets/questionIcons/Bike Parking.png'
export {default as noParkingIcon} from '../assets/questionIcons/No Parking.png'
export {default as bardAboveIcon} from '../assets/questionIcons/Bird Above.png'
export {default as dogCollarIcon} from '../assets/questionIcons/Dog Collar.png'
export {default as gasStationIcon} from '../assets/questionIcons/Gas Station.png'
export {default as fireplaeIcon} from '../assets/questionIcons/Fireplace.png'
export {default as roofingIcon} from '../assets/questionIcons/Roofing.png'
export {default as ceilingIcon} from '../assets/questionIcons/Ceiling Fan on.png'
export {default as petIcon} from '../assets/questionIcons/Pets.png'
export {default as kitchenIcon} from '../assets/questionIcons/Kitchen Room.png'
export {default as tumbleDryerIcon} from '../assets/questionIcons/Tumble Dryer.png'